### ISSUE TITLE
Issues on 32-bit Windows

### ISSUE THREAD

**Issue by Vercingetoriks** [hhrhhr/Lua-utils-for-Rebel-Galaxy#2]
Hello. I'm playing Rebel Galaxy on a 32-bit OS, so I can't use the package you provided. I've downloaded the 32-bit version of Lua 5.3 and used the lua_zlib.dll and lua_lfs.dll files from your package, but when trying to run it, I get this error:

"The application or DLL [...]\lua_zlib.dll is not a valid Windows image. Please check this against your installation diskette."

Could this be because that DLL is for a 64-bit system? To test this, I used the lua53.dll from your package and it has the same error. The one that comes with the 32bit Lua works fine.

Is there any way to work around this? I haven't been able to find out how to turn the files in https://github.com/brimworks/lua-zlib into a DLL, let alone how to make it 32bit-compatible.

**Comment by hhrhhr** [comment]
64-bit executables and DLLs do not work on 32-bit OS. lua-zlib and lua-lfs are only needed for the (pack|unpack).lua, for everything else it needs only Lua.

Workaround is simple — download 32-bit ready to use Lua, lua-zlib and lua-lfs, then edit (pack|unpack).lua:

```
local zlib = require("lua_zlib")
local lfs = require("lua_lfs")
```

and change the library names used by you, "zlib" and "lfs", for example.

Or compile them manually.
