### ISSUE TITLE
Precompiled dependencies link is broken

### ISSUE THREAD

**Issue by wobatt** [hhrhhr/Lua-utils-for-Rebel-Galaxy#3]
The download link for the lua-zlib and lua-lfs binaries, [this one](https://mega.nz/#!mxgGkYYY!SFJRF2feU_DdMu7L8dH-Syww-uUiO4_qbzDNLFstY8E), is broken.

Could these be reuploaded please?

**Comment by hhrhhr** [comment]
Use https://github.com/luarocks/luarocks/wiki/Download , Luke :)

**Comment by wobatt** [comment]
Tried it, can't get it to compile zlib, and I don't know how to get it to use a dll binary for zlib.

**Comment by hhrhhr** [comment]
````
luarocks install lua-zlib
luarocks install luafilesystem
````

**Comment by wobatt** [comment]
```
Installing https://luarocks.org/lua-zlib-1.2-0.src.rock
cl /nologo /MD /O2 -c -Folua_zlib.obj -IC:/Program Files (x86)/LuaRocks/include
lua_zlib.c -DLZLIB_COMPAT -Ic:/external/include
lua_zlib.c
link -dll -def:zlib.def -out:zlib.dll C:/Program Files (x86)/LuaRocks/lua5.1.lib
 lua_zlib.obj c:/external/lib/zlib.lib
Microsoft (R) Incremental Linker Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

LINK : fatal error LNK1104: cannot open file 'MSVCRT.lib'

Error: Build error: Failed compiling module zlib.dll
```

**Comment by hhrhhr** [comment]
This is not that repository issue. But ok, I uploaded the updated archive with Lua binaries and the necessary modules and updated the scripts for them.
